env: hosted
secret: FIXME

site_url: http://uptrace.local
# Whether to enable Let's Encrypt.
certmagic_enabled: false
# Whether to use Let's Encrypt staging environment.
certmagic_staging_ca: true

listen_http_addr: ':80'
listen_grpc_addr: ':4317'

ch_db_name: uptrace
ch_db_user: uptrace
ch_db_password: FIXME

ch_cluster: uptrace1
ch_distributed: false
ch_replicated: false

ch_shards:
  - name: shard1
    weight: 1

pg_db_name: uptrace
pg_db_user: uptrace
pg_db_password: FIXME

telegram_bot_token: ''

uptrace_version: '2.0.0-beta.5'
uptrace_license: ''
#uptrace_dsn: https://FIXME@api.uptrace.dev?grpc=4317
