---
- name: Add PostgreSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL apt repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name:
      - postgresql-{{ pg_version }}
      - postgresql-server-dev-{{ pg_version }}
      - postgresql-common
      - postgresql-contrib-{{ pg_version }}
    update_cache: yes
    state: latest
