---
- set_fact:
    pgbouncer_connections: '{{ [2, ansible_processor_vcpus*2] | max }}'
    shared_buffers: '{{ ansible_memtotal_mb // 10 }}'
    work_mem: '{{ ansible_memtotal_mb // 16 }}'
    maintenance_work_mem: '{{ [ansible_memtotal_mb // 8, 1024] | min }}'
    effective_cache_size: '{{ ansible_memtotal_mb // 2 }}'
  tags: [always]

- command: ls /var/lib/postgresql
  register: ls
  ignore_errors: yes

- import_tasks: install.yml
  when: ls is not defined or ls is failed
  tags: [install]

- name: start PostgreSQL
  service: name=postgresql state=started enabled=yes

- name: upload postgresql.conf
  template:
    src: '{{ pg_version }}/postgresql.conf'
    dest: /etc/postgresql/{{ pg_version }}/main/
    mode: 0640
    owner: postgres
    group: postgres
  tags: [config]
  notify: Restart PostgreSQL

- name: upload pg_hba.conf
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/{{ pg_version }}/main/
    owner: postgres
    group: postgres
    mode: 0640
  tags: [config]
  notify: Restart PostgreSQL

- name: standby.signal
  file:
    path: /var/lib/postgresql/{{ pg_version }}/main/standby.signal
    state: touch
    mode: '0644'
    owner: postgres
    group: postgres
  when: pg_primary_host is defined
  notify: Restart PostgreSQL

- name: Flush handlers
  meta: flush_handlers

- import_tasks: setup_db.yml
  when: pg_primary_host is not defined

- import_tasks: pgbouncer.yml
  tags: [pgbouncer]

- import_tasks: pgbackrest.yml
  when: pgbackrest is defined
  tags: [pgbackrest]
