---
- name: Install PgBouncer
  apt: pkg=pgbouncer

- name: Create PgBouncer config dir
  file: path=/etc/pgbouncer state=directory owner=postgres group=postgres mode=0755

- name: Configure PgBouncer service
  template:
    src: pgbouncer.service
    dest: /lib/systemd/system/pgbouncer.service
    owner: root
    group: root
    mode: 0644

- name: Upload PgBouncer config
  template: src={{ item }} dest=/etc/pgbouncer/ owner=postgres group=postgres mode=0640
  loop:
    - pgbouncer.ini
    - userlist.txt
  tags: [pgbouncer_config]
  notify: Restart PgBouncer
