---
- name: Create replicator user
  postgresql_user: name=replicator role_attr_flags=REPLICATION
  become_user: postgres

- name: Create db user
  postgresql_user:
    name: '{{ pg_db_user }}'
    password: '{{ pg_db_password }}'
    role_attr_flags: SUPERUSER
    encrypted: yes
  become_user: postgres

- name: Create database
  postgresql_db:
    name: '{{ pg_db_name }}'
    owner: postgres
    encoding: UTF-8
    template: template0
  become_user: postgres

- name: Grant privileges
  postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    obj: '{{ pg_db_name }}'
    role: '{{ pg_db_user }}'
  become_user: postgres
