---
- name: Create uptrace user
  user: name=uptrace groups=sudo shell=/bin/bash

- name: Create Uptrace data directory
  file: path=/var/lib/uptrace/ state=directory owner=uptrace group=uptrace mode=0755

- name: Create Uptrace config directory
  file: path=/etc/uptrace/ state=directory owner=uptrace group=uptrace mode=0755

- name: Record DEB architecture
  shell: dpkg --print-architecture
  register: arch

- name: Download Uptrace
  get_url:
    url: https://github.com/uptrace/uptrace/releases/download/v{{uptrace_version}}/uptrace_linux_{{arch.stdout}}
    dest: /usr/local/bin/uptrace
    owner: uptrace
    group: uptrace
    mode: 0755
    force: true
  notify: Restart Uptrace

- name: Check Uptrace binary
  command: /usr/local/bin/uptrace version

- set_fact:
    ch_shards:
      "{{ groups.clickhouse_server | map('extract', hostvars, 'ch_shard') | unique | sort }}"
  tags: [config]

- name: Upload Uptrace config
  template:
    src: config.yml
    dest: /etc/uptrace/config.yml
    owner: uptrace
    group: uptrace
    mode: 0644
  notify: Restart Uptrace
  tags: [config]

- import_tasks: systemd.yml
  tags: [systemd]

- import_tasks: logging.yml
  tags: [logging]

- name: Configure cron to delete old data
  cron:
    name: retention_check
    job:
      /usr/bin/flock /var/lock/uptrace_retention.lock /usr/local/bin/uptrace
      -config=/etc/uptrace/config.yml retention check
    weekday: '6' # Saturday
    hour: '0'
    minute: '15'
