---
- name: Init PostgreSQL migrations
  command: '/usr/local/bin/uptrace -config=/etc/uptrace/config.yml pg init'

- name: Init ClickHouse migrations
  command: '/usr/local/bin/uptrace -config=/etc/uptrace/config.yml ch init'

- name: Migrate PostgreSQL
  command: '/usr/local/bin/uptrace -config=/etc/uptrace/config.yml pg migrate'

- name: Migrate ClickHouse
  command: '/usr/local/bin/uptrace -config=/etc/uptrace/config.yml ch migrate'

- name: Create ClickHouse distributed tables
  command: '/usr/local/bin/uptrace -config=/etc/uptrace/config.yml ch dist'

- name: Seed database
  command: '/usr/local/bin/uptrace -config=/etc/uptrace/config.yml db seed'
