mailhog_arch: "{{ 'arm' if ansible_architecture == 'aarch64' else 'amd64' }}"
mailhog_install_dir: /opt/mailhog
mailhog_version: 1.0.0
mailhog_binary_url:
  'https://github.com/mailhog/MailHog/releases/download/v{{ mailhog_version }}/MailHog_linux_{{
  mailhog_arch }}'
